default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: sphere
  host: localhost
  username: puser
  password: 11111111

test:
  <<: *default
  database: sphere_test

production:
  <<: *default
  database: dfdijpt4qhj0be
